title: Your awesome title
author:
  name: Rogelio Prieto Alvarado	
  email: rogelioprieto@gmail.com

description: > # this means to ignore newlines until "show_excerpts:"
  Here I am writing the tips or  the solutions for problems I've faced as a GNU/Linux user.
  I hope this can help you!
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: rogelioprieto
    github:  rogelioprieto
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md


# Build settings
theme: minima
##TODO remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

#Enabling Excerpts on the Home Page
#To display post-excerpts on the Home Page
#show_excerpts: true


# theme: jekyll-theme-minima
#remote_theme: jekyll/minima
#remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll


##rogelioprieto github site!
